install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libreadline-dev valgrind
  - sudo apt-get install git-buildpackage
  - sudo apt-get install debhelper autotools-dev chrpath naturaldocs texlive-latex-base pkg-config
language: c
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#augeas"
script: git-buildpackage --git-ignore-branch
